### ISSUE TITLE
Restaurant coordinates

### ISSUE THREAD

**Issue by RedTn** [jrhender/asktoniapi#20]
If the longitude and latitude values of the restaurants are supplied by the api, I can make a map application that can point to the restaurants

**Comment by wfengk** [comment]
Sounds good, this isn't too hard

TODO: 

* Update data miner to include longitude and latitude values and rerun to get data
* Add longitude and latitude to Restaurant model (string or double?)
* Ensure these new fields are returned by the API

**Comment by RedTn** [comment]
> Add longitude and latitude to Restaurant model (string or double?)

Haha me and my company just had a debate about this...we decided to use double, but there are good arguments for using strings (no ambiguity on decimal places, potential rounding errors).
I'm fine either way

**Comment by wfengk** [comment]
This data should now be available
