### ISSUE TITLE
GET /Restaurant/:id

### ISSUE THREAD

**Issue by RedTn** [jrhender/asktoniapi#22]
Not currently working

**Comment by jrhender** [comment]
Ok, I will work on this. I think that it is because the id is now a more complex object, with a timestamp, machineID, pid, etc

**Comment by wfengk** [comment]
This could probably use some rework

Currently it does work but expects something like this as the parameter:
"59a30e0eb8837c783735d9c9"

That's the Object ID of the Mongo document in string form

**Comment by RedTn** [comment]
> Currently it does work but expects something like this as the parameter:
"59a30e0eb8837c783735d9c9"

That's fine, but this data is not being passed to the client in any form. If this was passed as part of the GET/restaurant payload then the client can use this

**Comment by jrhender** [comment]
I think it is being passed to the client. From the MongoDB ObjectID docs (https://docs.mongodb.com/manual/reference/method/ObjectId/) I think that the process ID, machine id, etc, can be converted in the hexadecimal value that Kevin mentioned. So I think either the client can send the data in the request body and the api can work with that or the client can convert the id object to string format and pass that through the query string?

**Comment by RedTn** [comment]
Thats fine, whats the formula to convert that ID object to the string

**Comment by RedTn** [comment]
Nvm, found a serializer for this [https://www.npmjs.com/package/bson](https://www.npmjs.com/package/bson)

**Comment by RedTn** [comment]
Nvm, found a serializer for this [https://www.npmjs.com/package/bson](https://www.npmjs.com/package/bson)

**Comment by jrhender** [comment]
My planned approach is client-side conversion, based on this post: https://stackoverflow.com/questions/34058200/is-there-any-way-to-convert-mongo-objectid-into-string-by-javascript-jquery

**Comment by RedTn** [comment]
This seems like quite a hacky way to retrieve the hex ID, apparently he needs to pad zeros as well. If the client must do this kind of post-processing on the returned data before it can be of use, I think it would make more sense for it to use a MongoDB supported driver, what do you think?

**Comment by RedTn** [comment]
On a side note, are you able to generate an ObjectID on your own and return a valid restaurant? I tried Kevin's (59a30e0eb8837c783735d9c9), and I tried the one on stackoverflow (565d3bf4cefddf1748d1fc5e) and it's returning the exact same restaurant object?

**Comment by jrhender** [comment]
Yeah, I think there is a Mongo driver for node but I couldn't find one for javascript in general. Which makes sense I think, cause it would be unusual to interface with the DB directly from the client app https://docs.mongodb.com/manual/applications/drivers/

**Comment by jrhender** [comment]
Let me get back to you on the ObjectID to return a valid restaurant haha

**Comment by jrhender** [comment]
But yeah, I know it's a little hacky/gluecodey but if we did want to make a client side utility function to handle this, would a Vue mixin make sense you think? https://vuejs.org/v2/guide/mixins.html

**Comment by RedTn** [comment]
Nevermind, seems like it will return some sort of default object if that's the case until you specify a valid ID like '59bd7dc7e5d6750d63f3e2d5'. I mean I could have the client check for this object to know it's an invalid GET, but the moment the schema changes on the API I will have to update that on the UI.

**Comment by RedTn** [comment]
Yes I would probably use a mixin to implement this so it's more reusable, but it'll still be the same code underneath the hood.
I'm still quite hesitant to go this route, but maybe if I had a better understanding about why this approach is better on the client than on the API I can see the benefit and proceed.

**Comment by jrhender** [comment]
Yeah, just thinking through the options. I mean, you're right, it is probably better to have the API do it

**Comment by jrhender** [comment]
So we are taking about the "API" approach, are we talking about the client can sending the id in the request body and then having the API work with that?
Or are you saying that you want the API to always respond with the string version of the ObjectIDs so the client never has to convert? If so, maybe we can follow the approach in this post: https://stackoverflow.com/questions/41345401/returning-objectid-as-a-string-from-asp-net-core

**Comment by RedTn** [comment]
The latter, it would be nice if the API would respond with the string version, something like
{id: '9138479abc', ...}. just like how the reviewIDs are being sent back in the GET(all)/restaurant API call

**Comment by jrhender** [comment]
ok, sounds good.
I'll try this method first https://stackoverflow.com/questions/7695730/mongodb-c-id-serialization-best-pattern
