### ISSUE TITLE
Duplicated restaurants

### ISSUE THREAD

**Issue by RedTn** [jrhender/asktoniapi#25]
The GET/restaurant API is returning duplicate restaurants for some cases

![image](https://user-images.githubusercontent.com/3923164/30764645-c038e764-9fa0-11e7-98dd-ff130e3ee70b.png)

**Comment by wfengk** [comment]
Looks like they are different restaurant locations

![mlab__cloud-hosted_mongodb](https://user-images.githubusercontent.com/8269985/30768104-16476d9e-9fb8-11e7-88ee-c4e57d7dcb10.jpg)
