### ISSUE TITLE
Copy data from staging to production

### ISSUE THREAD

**Issue by jrhender** [jrhender/asktoniapi#29]
Staging version of the asktoniapi is up and running: http://asktoniapi-staging.azurewebsites.net/swagger/ 

Need data in the mLab db though. I think the easiest way would be to copy the prod data to staging (and ideally automate this). Should be able to do an export of prod and then an import into staging

**Comment by wfengk** [comment]
Added <b>asktonidb-staging</b> as a separate instance in mLab
