### ISSUE TITLE
Basic Recommendation

### ISSUE THREAD

**Issue by wfengk** [jrhender/asktoniapi#31]
Hey @RedTn,

I'm implementing the first iteration of the recommendation algorithm. I'm thinking it will look like this: There will be a new endpoint in the API for recommendations

# Input (from client):
- Latitude (double)
- Longitude (double)
- Category (string)

# Output:

List of Restaurant objects

---
Thoughts?

**Comment by RedTn** [comment]
Sounds good, let's add paging/sorting etc. as well

**Comment by wfengk** [comment]
Hey @RedTn 

Added recommendation (with paging and sorting) to Staging

Can you add the functionality to the client?

http://asktoniapi-staging.azurewebsites.net/swagger/#/

> <b>Sample parameters:</b>
latitude: 49.2827
longitude: -123.1207
category: Pizza
pageOffset: 0 (optional)
pageLimit: 5 (optional)
sort: 1 (optional)

**Comment by RedTn** [comment]
@wfengk I'm not sure how the sort works as an integer param, but I could skip that for now.
What are all the possible values for **category** and the max/min values for lat/lng

**Comment by RedTn** [comment]
@wfengk Recommendation is also spelled 'Recomendation' in the endpoint
